# Generated by Django 5.0.6 on 2026-04-24 14:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransitionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module', models.CharField(choices=[('INCIDENT', 'Incident'), ('PROBLEM', 'Problem'), ('CHANGE', 'Change')], max_length=20)),
                ('record_id', models.UUIDField()),
                ('record_number', models.CharField(max_length=50)),
                ('from_state', models.CharField(max_length=50)),
                ('to_state', models.CharField(max_length=50)),
                ('transitioned_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('actions_executed', models.JSONField(default=list)),
                ('success', models.BooleanField(default=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('transitioned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-transitioned_at'],
            },
        ),
    ]
