# Generated by Django 5.0.6 on 2026-04-24 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
    ]
