import uuid
from django.db import models
from apps.organizations.models import Organization
from django.contrib.auth import get_user_model

User = get_user_model()

class CatalogCategory(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True, null=True)
    icon = models.CharField(max_length=50, blank=True, null=True)
    
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE, related_name='catalog_categories')
    parent = models.ForeignKey('self', on_delete=models.SET_NULL, null=True, blank=True, related_name='subcategories')
    
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "catalog_categories"
        verbose_name_plural = "Catalog Categories"

class CatalogItem(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=200)
    description = models.TextField()
    short_description = models.CharField(max_length=255)
    
    category = models.ForeignKey(CatalogCategory, on_delete=models.CASCADE, related_name='items')
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE, related_name='catalog_items')
    
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    recurring_price = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    
    is_active = models.BooleanField(default=True)
    picture = models.URLField(blank=True, null=True)
    
    # Workflow / Execution Plan link
    workflow = models.ForeignKey('workflows.Workflow', on_delete=models.SET_NULL, null=True, blank=True)
    
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "catalog_items"

class ServiceRequest(models.Model):
    """The 'REQ' record - high level wrapper for a shopping cart order."""
    class State(models.TextChoices):
        DRAFT = "DRAFT", "Draft"
        PENDING_APPROVAL = "PENDING_APPROVAL", "Pending Approval"
        APPROVED = "APPROVED", "Approved"
        FULFILLMENT = "FULFILLMENT", "Work in Progress"
        CLOSED = "CLOSED", "Closed"
        CANCELLED = "CANCELLED", "Cancelled"

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    number = models.CharField(max_length=50, unique=True, db_index=True)
    
    requested_for = models.ForeignKey(User, on_delete=models.PROTECT, related_name='service_requests')
    opened_by = models.ForeignKey(User, on_delete=models.PROTECT, related_name='opened_service_requests')
    
    state = models.CharField(max_length=20, choices=State.choices, default=State.DRAFT)
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE, related_name='service_requests')
    
    total_price = models.DecimalField(max_digits=12, decimal_places=2, default=0.00)
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "service_requests"

class RequestedItem(models.Model):
    """The 'RITM' record - specific instance of a catalog item."""
    class State(models.TextChoices):
        PENDING_APPROVAL = "PENDING_APPROVAL", "Pending Approval"
        APPROVED = "APPROVED", "Approved"
        FULFILLMENT = "FULFILLMENT", "Work in Progress"
        COMPLETED = "COMPLETED", "Completed"
        CANCELLED = "CANCELLED", "Cancelled"

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    number = models.CharField(max_length=50, unique=True, db_index=True)
    
    request = models.ForeignKey(ServiceRequest, on_delete=models.CASCADE, related_name='items')
    catalog_item = models.ForeignKey(CatalogItem, on_delete=models.PROTECT)
    
    state = models.CharField(max_length=20, choices=State.choices, default=State.PENDING_APPROVAL)
    quantity = models.IntegerField(default=1)
    
    # Option data (dynamic variables)
    variables = models.JSONField(default=dict, blank=True)
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "requested_items"

class CatalogTask(models.Model):
    """The 'SCTASK' record - fulfillment tasks generated by workflow."""
    class State(models.TextChoices):
        OPEN = "OPEN", "Open"
        IN_PROGRESS = "IN_PROGRESS", "Work in Progress"
        CLOSED_COMPLETE = "CLOSED_COMPLETE", "Closed Complete"
        CLOSED_INCOMPLETE = "CLOSED_INCOMPLETE", "Closed Incomplete"
        CLOSED_SKIPPED = "CLOSED_SKIPPED", "Closed Skipped"

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    number = models.CharField(max_length=50, unique=True, db_index=True)
    
    ritm = models.ForeignKey(RequestedItem, on_delete=models.CASCADE, related_name='tasks')
    
    short_description = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    
    state = models.CharField(max_length=20, choices=State.choices, default=State.OPEN)
    
    assigned_to = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    assignment_group = models.ForeignKey('teams.Team', on_delete=models.SET_NULL, null=True, blank=True)
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "catalog_tasks"
